config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :flats
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
# frozen_string_literal: true

class Flat < ApplicationRecord
  scope :within_radius, lambda { |lat, lng, meter|
                          where('earth_box(ll_to_earth(?, ?), ?) @> ll_to_earth(latitude, longitude)', lat, lng, meter)
                        }

  belongs_to :user

  has_many :neighboorhood_flats, class_name: 'NeighborhoodFlat', dependent: :delete_all
  has_many :neighborhoods, through: :neighboorhood_flats

  validates :name, presence: true
  validates :latitude, presence: true, numericality: true
  validates :longitude, presence: true, numericality: true
end

app/models/neighborhood.rb
# frozen_string_literal: true

class Neighborhood < ApplicationRecord
  has_many :neighborhood_flats, class_name: 'NeighborhoodFlat', dependent: :delete_all
  has_many :flats, through: :neighborhood_flats
  has_many :users, through: :flats

  validates :name, presence: true
  validates :latitude, presence: true, numericality: true
  validates :longitude, presence: true, numericality: true
  validates :radius, presence: true, numericality: true

  after_create :set_nearest_flats

  # get nearest flat based on radius meters
  def find_nearest_flats
    Flat.within_radius(latitude, longitude, radius)
  end

  private

  def set_nearest_flats
    find_nearest_flats.each do |flat|
      neighborhood_flats.create!(flat: flat)
    end
  end
end

app/models/neighborhood_flat.rb
# frozen_string_literal: true

class NeighborhoodFlat < ApplicationRecord
  belongs_to :flat
  belongs_to :neighborhood
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :flats, dependent: :destroy
  has_many :neighborhoods, through: :flats

  validates :name, presence: true
  validates :email, presence: true, email: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
# frozen_string_literal: true

class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  # GET /flats
  def index
    @flats = Flat.includes(:user).all
  end

  # GET /flats/1
  def show; end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit; end

  # POST /flats
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flats_path, notice: t('flat-created') }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  def update
    if @flat.update(flat_params)
      format.html { redirect_to flats_path, notice: t('flat-updated') }
    else
      format.html { render :edit, status: :unprocessable_entity }
      format.turbo_stream { render :form_update, status: :unprocessable_entity }
    end
  end

  # DELETE /flats/1
  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_path, notice: t('flat-destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:user_id, :name, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: t('user-created') }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: t('user-updated') }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, notice: t('user-destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/flats_helper.rb
# frozen_string_literal: true

module FlatsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/flats/_flat.html.erb
<td style="width: 15%"><%= flat.user.name %></td>
<td style="width: 15%"><%= flat.name %></td>
<td style="width: 15%"><%= flat.latitude %></td>
<td style="width: 15%"><%= flat.longitude %></td>
<td style="width: 50%">
  <%= link_to "Show", flat, class: "btn btn-secondary", data: { turbo_frame: "remote_modal" } %>
  <%= link_to "Edit", edit_flat_path(flat), class: "btn btn-success", data: { turbo_frame: "remote_modal" } %>
  <%= link_to "Delete", flat, class: "btn btn-danger", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
</td>

app/views/flats/_form.html.erb
<%= form_with(model: flat) do |form| %>
  <div class="mb-3">
    <%= form.label :user_id, style: "display: block", class: "form-label" %>
    <%= form.select :user_id, User.all.collect { |u| [ u.name, u.id ] },{}, class: "form-control" %>
    <div style="color: red">
      <% if flat.errors.include?(:user) %>
          <% flat.errors.full_messages_for(:user).each do |error_message| %>
            <%= error_message %>.
          <% end %>
      <% end %>
    </div>
  </div>
  
  <div class="mb-3">
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
    <div style="color: red">
      <% if flat.errors.include?(:name) %>
          <% flat.errors.full_messages_for(:name).each do |error_message| %>
            <%= error_message %>.
          <% end %>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :latitude, style: "display: block", class: "form-label" %>
    <%= form.text_field :latitude, class: "form-control" %>
    <div style="color: red">
      <% if flat.errors.include?(:latitude) %>
          <% flat.errors.full_messages_for(:latitude).each do |error_message| %>
            <%= error_message %>.
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="mb-3">
    <%= form.label :longitude, style: "display: block", class: "form-label" %>
    <%= form.text_field :longitude, class: "form-control" %>
    <div style="color: red">
      <% if flat.errors.include?(:longitude) %>
          <% flat.errors.full_messages_for(:longitude).each do |error_message| %>
            <%= error_message %>.
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/flats/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newFlatRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newFlatRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/flats/edit.html.erb
<%= render "remote_modal", title: "Edit flat" do %>
  <%= render "form", flat: @flat %>
<% end %>

app/views/flats/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form", flat: @flat %>
<% end %>

app/views/flats/index.html.erb
<div class="card-header p-3">
  <h5 class="mb-0">Users</h5>
</div>

<div class="text-end p-3">
  <p style="color: green"><%= notice %></p>
  <%= link_to "New flat", new_flat_path, class: "btn btn-primary", data: { turbo_frame: "remote_modal" } %>
</div>

<div id="users" class="card-body" data-mdb-perfect-scrollbar="true" style="position: relative; height: 400px">
  <table>
    <thead>
      <tr>
        <th scope="col">Owner</th>
        <th scope="col">Name</th>
        <th scope="col">Latitude</th>
        <th scope="col">Longitude</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @flats.each do |flat| %>
        <tr id="flat_<%= flat.id %>", scope="row">
          <%= render flat %>
        <tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/flats/new.html.erb
<%= render "remote_modal", title: "New flat" do %>
  <%= render "form", flat: @flat %>
<% end %>

app/views/flats/show.html.erb
<%= render "remote_modal", title: "Flat detail" do %>
<div class="col-lg-8">
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Owner</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @flat.user.name %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Name</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @flat.name %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Latitude</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @flat.latitude %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Longitude</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @flat.longitude %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Neighborhods</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @flat.neighborhoods.map(&:name).join(", ") %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neighboor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section class="vh-100" style="background-color: #eee;">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-12 col-xl-10">
            <div class="card">
              <%= yield %>
              <%= turbo_frame_tag "remote_modal", target: "_top" %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div class="mb-3">
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
    <div style="color: red">
      <% if user.errors.include?(:name) %>
          <% user.errors.full_messages_for(:name).each do |error_message| %>
            <%= error_message %>.
          <% end %>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block", class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
    <div style="color: red">
      <% if user.errors.include?(:email) %>
          <% user.errors.full_messages_for(:name).each do |error_message| %>
            <%= error_message %>.
          <% end %>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/users/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>
  <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newUserRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content" id="modal_content">
        <div class="modal-header">
          <h4 class="modal-title" id="newUserRemoteModalLabel"><%= title %></h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body remote_modal_body" id="remote_modal_body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<td style="width: 25%"><%= user.name %></td>
<td style="width: 25%"><%= user.email %></td>
<td style="width: 50%">
  <%= link_to "Show", user, class: "btn btn-secondary", data: { turbo_frame: "remote_modal" } %>
  <%= link_to "Edit", edit_user_path(user), class: "btn btn-success", data: { turbo_frame: "remote_modal" } %>
  <%= link_to "Delete", user, class: "btn btn-danger", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
</td>

app/views/users/edit.html.erb
<%= render "remote_modal", title: "Edit user" do %>
  <%= render "form", user: @user %>
<% end %>

app/views/users/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form", user: @user %>
<% end %>

app/views/users/index.html.erb
<div class="card-header p-3">
  <h5 class="mb-0">Users</h5>
</div>

<div class="text-end p-3">
  <p style="color: green"><%= notice %></p>
  <%= link_to "New user", new_user_path, class: "btn btn-primary", data: { turbo_frame: "remote_modal" } %>
</div>

<div id="users" class="card-body" data-mdb-perfect-scrollbar="true" style="position: relative; height: 400px">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">E-mail</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr id="user_<%= user.id %>" scope="row">
          <%= render user %>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

app/views/users/new.html.erb
<%= render "remote_modal", title: "New user" do %>
  <%= render "form", user: @user %>
<% end %>

app/views/users/show.html.erb
<%= render "remote_modal", title: "#{@user.name} (#{@user.email})" do %>
<h3>Flats</h3>
<div id="users" class="card-body" data-mdb-perfect-scrollbar="true" style="position: relative; height: 400px">
  <table>
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Latitude</th>
        <th scope="col">Longitude</th>
      </tr>
    </thead>
    <tbody>
      <% @user.flats.each do |flat| %>
        <tr id="flat_<%= flat.id %>", scope="row">
          <td style="width: 15%"><%= flat.name %></td>
          <td style="width: 15%"><%= flat.latitude %></td>
          <td style="width: 15%"><%= flat.longitude %></td>
        <tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>